# Generated by Django 4.1.2 on 2022-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_created_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
    ]
