# Generated by Django 4.1.2 on 2022-10-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_created_at_account_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='birthday',
        ),
        migrations.AddField(
            model_name='account',
            name='count_subscribers',
            field=models.IntegerField(default=0, verbose_name='Count subscribers'),
        ),
        migrations.AddField(
            model_name='account',
            name='count_subscriptions',
            field=models.IntegerField(default=0, verbose_name='Count subscriptions'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
